spring.application.name=rag-demo


# Spring AI OpenAI Configuration
spring.ai.openai.embedding.model=text-embedding-3-small
spring.ai.openai.embedding.dimensions=768

spring.ai.openai.chat.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.model=gpt-5-mini

# Spring AI PgVector Configuration
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.schema-validation=true
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.max-document-batch-size=10000
spring.ai.vectorstore.pgvector.table-name=vector_store

spring.datasource.url=jdbc:postgresql://localhost:5432/rag_demo
spring.datasource.username=prajvalpase