spring.application.name=rag-demo


# Spring AI OpenAI Configuration
spring.ai.openai.embedding.options.model=text-embedding-3-small
spring.ai.openai.embedding.options.dimensions=768

spring.ai.openai.chat.base-url=https://api.openai.com
spring.ai.openai.chat.api-key=
spring.ai.openai.chat.options.model=gpt-4.1-mini

# Spring AI PgVector Configuration
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.max-document-batch-size=10000
spring.ai.vectorstore.pgvector.schema-validation=true
spring.ai.vectorstore.pgvector.table-name=vector_store